// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// roundDecimal
double roundDecimal(double number, int digits);
RcppExport SEXP _isoRelate_roundDecimal(SEXP numberSEXP, SEXP digitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type number(numberSEXP);
    Rcpp::traits::input_parameter< int >::type digits(digitsSEXP);
    rcpp_result_gen = Rcpp::wrap(roundDecimal(number, digits));
    return rcpp_result_gen;
END_RCPP
}
// emissionProbHH
double emissionProbHH(double pop_allele_freq, int genotype_1, int genotype_2, int ibd);
RcppExport SEXP _isoRelate_emissionProbHH(SEXP pop_allele_freqSEXP, SEXP genotype_1SEXP, SEXP genotype_2SEXP, SEXP ibdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type pop_allele_freq(pop_allele_freqSEXP);
    Rcpp::traits::input_parameter< int >::type genotype_1(genotype_1SEXP);
    Rcpp::traits::input_parameter< int >::type genotype_2(genotype_2SEXP);
    Rcpp::traits::input_parameter< int >::type ibd(ibdSEXP);
    rcpp_result_gen = Rcpp::wrap(emissionProbHH(pop_allele_freq, genotype_1, genotype_2, ibd));
    return rcpp_result_gen;
END_RCPP
}
// emissionProbHD
double emissionProbHD(double pop_allele_freq, int genotype_1, int genotype_2, int ibd, int male_column, int female_column);
RcppExport SEXP _isoRelate_emissionProbHD(SEXP pop_allele_freqSEXP, SEXP genotype_1SEXP, SEXP genotype_2SEXP, SEXP ibdSEXP, SEXP male_columnSEXP, SEXP female_columnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type pop_allele_freq(pop_allele_freqSEXP);
    Rcpp::traits::input_parameter< int >::type genotype_1(genotype_1SEXP);
    Rcpp::traits::input_parameter< int >::type genotype_2(genotype_2SEXP);
    Rcpp::traits::input_parameter< int >::type ibd(ibdSEXP);
    Rcpp::traits::input_parameter< int >::type male_column(male_columnSEXP);
    Rcpp::traits::input_parameter< int >::type female_column(female_columnSEXP);
    rcpp_result_gen = Rcpp::wrap(emissionProbHD(pop_allele_freq, genotype_1, genotype_2, ibd, male_column, female_column));
    return rcpp_result_gen;
END_RCPP
}
// emissionProbDD
double emissionProbDD(double pop_allele_freq, int genotype_1, int genotype_2, int ibd);
RcppExport SEXP _isoRelate_emissionProbDD(SEXP pop_allele_freqSEXP, SEXP genotype_1SEXP, SEXP genotype_2SEXP, SEXP ibdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type pop_allele_freq(pop_allele_freqSEXP);
    Rcpp::traits::input_parameter< int >::type genotype_1(genotype_1SEXP);
    Rcpp::traits::input_parameter< int >::type genotype_2(genotype_2SEXP);
    Rcpp::traits::input_parameter< int >::type ibd(ibdSEXP);
    rcpp_result_gen = Rcpp::wrap(emissionProbDD(pop_allele_freq, genotype_1, genotype_2, ibd));
    return rcpp_result_gen;
END_RCPP
}
// transitionProbHH
double transitionProbHH(double omega_0, int meiosis, double dist_cM, int ibd_current, int ibd_previous);
RcppExport SEXP _isoRelate_transitionProbHH(SEXP omega_0SEXP, SEXP meiosisSEXP, SEXP dist_cMSEXP, SEXP ibd_currentSEXP, SEXP ibd_previousSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type omega_0(omega_0SEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< double >::type dist_cM(dist_cMSEXP);
    Rcpp::traits::input_parameter< int >::type ibd_current(ibd_currentSEXP);
    Rcpp::traits::input_parameter< int >::type ibd_previous(ibd_previousSEXP);
    rcpp_result_gen = Rcpp::wrap(transitionProbHH(omega_0, meiosis, dist_cM, ibd_current, ibd_previous));
    return rcpp_result_gen;
END_RCPP
}
// transitionProbHD
double transitionProbHD(double omega_0, int meiosis, double dist_cM, int ibd_current, int ibd_previous);
RcppExport SEXP _isoRelate_transitionProbHD(SEXP omega_0SEXP, SEXP meiosisSEXP, SEXP dist_cMSEXP, SEXP ibd_currentSEXP, SEXP ibd_previousSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type omega_0(omega_0SEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< double >::type dist_cM(dist_cMSEXP);
    Rcpp::traits::input_parameter< int >::type ibd_current(ibd_currentSEXP);
    Rcpp::traits::input_parameter< int >::type ibd_previous(ibd_previousSEXP);
    rcpp_result_gen = Rcpp::wrap(transitionProbHD(omega_0, meiosis, dist_cM, ibd_current, ibd_previous));
    return rcpp_result_gen;
END_RCPP
}
// transitionProbDD
double transitionProbDD(double omega_0, double omega_1, double omega_2, int meiosis, double dist_cM, int ibd_current, int ibd_previous);
RcppExport SEXP _isoRelate_transitionProbDD(SEXP omega_0SEXP, SEXP omega_1SEXP, SEXP omega_2SEXP, SEXP meiosisSEXP, SEXP dist_cMSEXP, SEXP ibd_currentSEXP, SEXP ibd_previousSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type omega_0(omega_0SEXP);
    Rcpp::traits::input_parameter< double >::type omega_1(omega_1SEXP);
    Rcpp::traits::input_parameter< double >::type omega_2(omega_2SEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< double >::type dist_cM(dist_cMSEXP);
    Rcpp::traits::input_parameter< int >::type ibd_current(ibd_currentSEXP);
    Rcpp::traits::input_parameter< int >::type ibd_previous(ibd_previousSEXP);
    rcpp_result_gen = Rcpp::wrap(transitionProbDD(omega_0, omega_1, omega_2, meiosis, dist_cM, ibd_current, ibd_previous));
    return rcpp_result_gen;
END_RCPP
}
// genotypeErrorH
double genotypeErrorH(int truth, int observed, double error);
RcppExport SEXP _isoRelate_genotypeErrorH(SEXP truthSEXP, SEXP observedSEXP, SEXP errorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type truth(truthSEXP);
    Rcpp::traits::input_parameter< int >::type observed(observedSEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    rcpp_result_gen = Rcpp::wrap(genotypeErrorH(truth, observed, error));
    return rcpp_result_gen;
END_RCPP
}
// genotypeErrorD
double genotypeErrorD(int truth, int observed, double error);
RcppExport SEXP _isoRelate_genotypeErrorD(SEXP truthSEXP, SEXP observedSEXP, SEXP errorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type truth(truthSEXP);
    Rcpp::traits::input_parameter< int >::type observed(observedSEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    rcpp_result_gen = Rcpp::wrap(genotypeErrorD(truth, observed, error));
    return rcpp_result_gen;
END_RCPP
}
// trueGenotypes
IntegerMatrix trueGenotypes(int gender_1, int gender_2);
RcppExport SEXP _isoRelate_trueGenotypes(SEXP gender_1SEXP, SEXP gender_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type gender_1(gender_1SEXP);
    Rcpp::traits::input_parameter< int >::type gender_2(gender_2SEXP);
    rcpp_result_gen = Rcpp::wrap(trueGenotypes(gender_1, gender_2));
    return rcpp_result_gen;
END_RCPP
}
// emissionProbMissingGeno
double emissionProbMissingGeno(double pop_allele_freq, int genotype_1, int genotype_2, double error, int gender_1, int gender_2, int ibd_j);
RcppExport SEXP _isoRelate_emissionProbMissingGeno(SEXP pop_allele_freqSEXP, SEXP genotype_1SEXP, SEXP genotype_2SEXP, SEXP errorSEXP, SEXP gender_1SEXP, SEXP gender_2SEXP, SEXP ibd_jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type pop_allele_freq(pop_allele_freqSEXP);
    Rcpp::traits::input_parameter< int >::type genotype_1(genotype_1SEXP);
    Rcpp::traits::input_parameter< int >::type genotype_2(genotype_2SEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    Rcpp::traits::input_parameter< int >::type gender_1(gender_1SEXP);
    Rcpp::traits::input_parameter< int >::type gender_2(gender_2SEXP);
    Rcpp::traits::input_parameter< int >::type ibd_j(ibd_jSEXP);
    rcpp_result_gen = Rcpp::wrap(emissionProbMissingGeno(pop_allele_freq, genotype_1, genotype_2, error, gender_1, gender_2, ibd_j));
    return rcpp_result_gen;
END_RCPP
}
// calculateAlpha
NumericMatrix calculateAlpha(const int number_states, NumericVector initial_prob, int meiosis, const int number_snps, IntegerMatrix genotypes, NumericVector pop_allele_freqs, NumericVector positions_cM, double error, int gender_1, int gender_2);
RcppExport SEXP _isoRelate_calculateAlpha(SEXP number_statesSEXP, SEXP initial_probSEXP, SEXP meiosisSEXP, SEXP number_snpsSEXP, SEXP genotypesSEXP, SEXP pop_allele_freqsSEXP, SEXP positions_cMSEXP, SEXP errorSEXP, SEXP gender_1SEXP, SEXP gender_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type number_states(number_statesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_prob(initial_probSEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< const int >::type number_snps(number_snpsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pop_allele_freqs(pop_allele_freqsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type positions_cM(positions_cMSEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    Rcpp::traits::input_parameter< int >::type gender_1(gender_1SEXP);
    Rcpp::traits::input_parameter< int >::type gender_2(gender_2SEXP);
    rcpp_result_gen = Rcpp::wrap(calculateAlpha(number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2));
    return rcpp_result_gen;
END_RCPP
}
// calculateScale
NumericVector calculateScale(const int number_states, NumericVector initial_prob, int meiosis, const int number_snps, IntegerMatrix genotypes, NumericVector pop_allele_freqs, NumericVector positions_cM, double error, int gender_1, int gender_2);
RcppExport SEXP _isoRelate_calculateScale(SEXP number_statesSEXP, SEXP initial_probSEXP, SEXP meiosisSEXP, SEXP number_snpsSEXP, SEXP genotypesSEXP, SEXP pop_allele_freqsSEXP, SEXP positions_cMSEXP, SEXP errorSEXP, SEXP gender_1SEXP, SEXP gender_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type number_states(number_statesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_prob(initial_probSEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< const int >::type number_snps(number_snpsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pop_allele_freqs(pop_allele_freqsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type positions_cM(positions_cMSEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    Rcpp::traits::input_parameter< int >::type gender_1(gender_1SEXP);
    Rcpp::traits::input_parameter< int >::type gender_2(gender_2SEXP);
    rcpp_result_gen = Rcpp::wrap(calculateScale(number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2));
    return rcpp_result_gen;
END_RCPP
}
// calculateBeta
NumericMatrix calculateBeta(const int number_states, NumericVector initial_prob, int meiosis, const int number_snps, IntegerMatrix genotypes, NumericVector pop_allele_freqs, NumericVector positions_cM, NumericVector scale, double error, int gender_1, int gender_2);
RcppExport SEXP _isoRelate_calculateBeta(SEXP number_statesSEXP, SEXP initial_probSEXP, SEXP meiosisSEXP, SEXP number_snpsSEXP, SEXP genotypesSEXP, SEXP pop_allele_freqsSEXP, SEXP positions_cMSEXP, SEXP scaleSEXP, SEXP errorSEXP, SEXP gender_1SEXP, SEXP gender_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type number_states(number_statesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_prob(initial_probSEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< const int >::type number_snps(number_snpsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pop_allele_freqs(pop_allele_freqsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type positions_cM(positions_cMSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    Rcpp::traits::input_parameter< int >::type gender_1(gender_1SEXP);
    Rcpp::traits::input_parameter< int >::type gender_2(gender_2SEXP);
    rcpp_result_gen = Rcpp::wrap(calculateBeta(number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, scale, error, gender_1, gender_2));
    return rcpp_result_gen;
END_RCPP
}
// calculateViterbi
IntegerVector calculateViterbi(const int number_states, NumericVector initial_prob, int meiosis, const int number_snps, IntegerMatrix genotypes, NumericVector pop_allele_freqs, NumericVector positions_cM, double error, int gender_1, int gender_2);
RcppExport SEXP _isoRelate_calculateViterbi(SEXP number_statesSEXP, SEXP initial_probSEXP, SEXP meiosisSEXP, SEXP number_snpsSEXP, SEXP genotypesSEXP, SEXP pop_allele_freqsSEXP, SEXP positions_cMSEXP, SEXP errorSEXP, SEXP gender_1SEXP, SEXP gender_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type number_states(number_statesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_prob(initial_probSEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< const int >::type number_snps(number_snpsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pop_allele_freqs(pop_allele_freqsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type positions_cM(positions_cMSEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    Rcpp::traits::input_parameter< int >::type gender_1(gender_1SEXP);
    Rcpp::traits::input_parameter< int >::type gender_2(gender_2SEXP);
    rcpp_result_gen = Rcpp::wrap(calculateViterbi(number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2));
    return rcpp_result_gen;
END_RCPP
}
// calculateGamma
NumericMatrix calculateGamma(const int number_states, NumericVector initial_prob, int meiosis, const int number_snps, IntegerMatrix genotypes, NumericVector pop_allele_freqs, NumericVector positions_cM, double error, int gender_1, int gender_2);
RcppExport SEXP _isoRelate_calculateGamma(SEXP number_statesSEXP, SEXP initial_probSEXP, SEXP meiosisSEXP, SEXP number_snpsSEXP, SEXP genotypesSEXP, SEXP pop_allele_freqsSEXP, SEXP positions_cMSEXP, SEXP errorSEXP, SEXP gender_1SEXP, SEXP gender_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type number_states(number_statesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_prob(initial_probSEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< const int >::type number_snps(number_snpsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pop_allele_freqs(pop_allele_freqsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type positions_cM(positions_cMSEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    Rcpp::traits::input_parameter< int >::type gender_1(gender_1SEXP);
    Rcpp::traits::input_parameter< int >::type gender_2(gender_2SEXP);
    rcpp_result_gen = Rcpp::wrap(calculateGamma(number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2));
    return rcpp_result_gen;
END_RCPP
}
// calculateLogLikelihood
double calculateLogLikelihood(const int number_states, NumericVector initial_prob, int meiosis, const int number_snps, IntegerMatrix genotypes, NumericVector pop_allele_freqs, NumericVector positions_cM, double error, int gender_1, int gender_2);
RcppExport SEXP _isoRelate_calculateLogLikelihood(SEXP number_statesSEXP, SEXP initial_probSEXP, SEXP meiosisSEXP, SEXP number_snpsSEXP, SEXP genotypesSEXP, SEXP pop_allele_freqsSEXP, SEXP positions_cMSEXP, SEXP errorSEXP, SEXP gender_1SEXP, SEXP gender_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type number_states(number_statesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_prob(initial_probSEXP);
    Rcpp::traits::input_parameter< int >::type meiosis(meiosisSEXP);
    Rcpp::traits::input_parameter< const int >::type number_snps(number_snpsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pop_allele_freqs(pop_allele_freqsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type positions_cM(positions_cMSEXP);
    Rcpp::traits::input_parameter< double >::type error(errorSEXP);
    Rcpp::traits::input_parameter< int >::type gender_1(gender_1SEXP);
    Rcpp::traits::input_parameter< int >::type gender_2(gender_2SEXP);
    rcpp_result_gen = Rcpp::wrap(calculateLogLikelihood(number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2));
    return rcpp_result_gen;
END_RCPP
}
// bVectorHH
IntegerVector bVectorHH(IntegerMatrix genotypes);
RcppExport SEXP _isoRelate_bVectorHH(SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    rcpp_result_gen = Rcpp::wrap(bVectorHH(genotypes));
    return rcpp_result_gen;
END_RCPP
}
// AmatrixHH
NumericMatrix AmatrixHH(NumericVector pop_allele_freqs, IntegerMatrix genotypes);
RcppExport SEXP _isoRelate_AmatrixHH(SEXP pop_allele_freqsSEXP, SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pop_allele_freqs(pop_allele_freqsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    rcpp_result_gen = Rcpp::wrap(AmatrixHH(pop_allele_freqs, genotypes));
    return rcpp_result_gen;
END_RCPP
}
// bVectorHD
IntegerVector bVectorHD(IntegerMatrix genotypes);
RcppExport SEXP _isoRelate_bVectorHD(SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    rcpp_result_gen = Rcpp::wrap(bVectorHD(genotypes));
    return rcpp_result_gen;
END_RCPP
}
// AmatrixHD
NumericMatrix AmatrixHD(NumericVector pop_allele_freqs, IntegerMatrix genotypes);
RcppExport SEXP _isoRelate_AmatrixHD(SEXP pop_allele_freqsSEXP, SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pop_allele_freqs(pop_allele_freqsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    rcpp_result_gen = Rcpp::wrap(AmatrixHD(pop_allele_freqs, genotypes));
    return rcpp_result_gen;
END_RCPP
}
// bVectorDD
IntegerVector bVectorDD(IntegerMatrix genotypes);
RcppExport SEXP _isoRelate_bVectorDD(SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    rcpp_result_gen = Rcpp::wrap(bVectorDD(genotypes));
    return rcpp_result_gen;
END_RCPP
}
// AmatrixDD
NumericMatrix AmatrixDD(NumericVector pop_allele_freqs, IntegerMatrix genotypes);
RcppExport SEXP _isoRelate_AmatrixDD(SEXP pop_allele_freqsSEXP, SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pop_allele_freqs(pop_allele_freqsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    rcpp_result_gen = Rcpp::wrap(AmatrixDD(pop_allele_freqs, genotypes));
    return rcpp_result_gen;
END_RCPP
}
// IBDMatrix
IntegerMatrix IBDMatrix(CharacterVector chromosomes, NumericVector positions_bp, int number_pairs, IntegerVector ibd_pairs_colnumbers, CharacterVector ibd_chromosomes, NumericVector ibd_start_bp, NumericVector ibd_stop_bp);
RcppExport SEXP _isoRelate_IBDMatrix(SEXP chromosomesSEXP, SEXP positions_bpSEXP, SEXP number_pairsSEXP, SEXP ibd_pairs_colnumbersSEXP, SEXP ibd_chromosomesSEXP, SEXP ibd_start_bpSEXP, SEXP ibd_stop_bpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type chromosomes(chromosomesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type positions_bp(positions_bpSEXP);
    Rcpp::traits::input_parameter< int >::type number_pairs(number_pairsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ibd_pairs_colnumbers(ibd_pairs_colnumbersSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ibd_chromosomes(ibd_chromosomesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ibd_start_bp(ibd_start_bpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ibd_stop_bp(ibd_stop_bpSEXP);
    rcpp_result_gen = Rcpp::wrap(IBDMatrix(chromosomes, positions_bp, number_pairs, ibd_pairs_colnumbers, ibd_chromosomes, ibd_start_bp, ibd_stop_bp));
    return rcpp_result_gen;
END_RCPP
}
// calculatePopAlleleFreq
NumericVector calculatePopAlleleFreq(IntegerMatrix genotypes, IntegerVector moi);
RcppExport SEXP _isoRelate_calculatePopAlleleFreq(SEXP genotypesSEXP, SEXP moiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type moi(moiSEXP);
    rcpp_result_gen = Rcpp::wrap(calculatePopAlleleFreq(genotypes, moi));
    return rcpp_result_gen;
END_RCPP
}
// calculateMissingness
NumericVector calculateMissingness(IntegerMatrix genotypes);
RcppExport SEXP _isoRelate_calculateMissingness(SEXP genotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes(genotypesSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateMissingness(genotypes));
    return rcpp_result_gen;
END_RCPP
}
// groupPairs
CharacterMatrix groupPairs(CharacterVector group);
RcppExport SEXP _isoRelate_groupPairs(SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(groupPairs(group));
    return rcpp_result_gen;
END_RCPP
}
// isolatePairs
CharacterMatrix isolatePairs(CharacterVector fid, CharacterVector iid);
RcppExport SEXP _isoRelate_isolatePairs(SEXP fidSEXP, SEXP iidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type fid(fidSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type iid(iidSEXP);
    rcpp_result_gen = Rcpp::wrap(isolatePairs(fid, iid));
    return rcpp_result_gen;
END_RCPP
}
// haplotypeToGenotype
IntegerMatrix haplotypeToGenotype(IntegerMatrix haplotypes, IntegerVector moi);
RcppExport SEXP _isoRelate_haplotypeToGenotype(SEXP haplotypesSEXP, SEXP moiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type haplotypes(haplotypesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type moi(moiSEXP);
    rcpp_result_gen = Rcpp::wrap(haplotypeToGenotype(haplotypes, moi));
    return rcpp_result_gen;
END_RCPP
}
// IBDLabel
IntegerVector IBDLabel(IntegerVector snp_id, const int number_snps);
RcppExport SEXP _isoRelate_IBDLabel(SEXP snp_idSEXP, SEXP number_snpsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type snp_id(snp_idSEXP);
    Rcpp::traits::input_parameter< const int >::type number_snps(number_snpsSEXP);
    rcpp_result_gen = Rcpp::wrap(IBDLabel(snp_id, number_snps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_isoRelate_roundDecimal", (DL_FUNC) &_isoRelate_roundDecimal, 2},
    {"_isoRelate_emissionProbHH", (DL_FUNC) &_isoRelate_emissionProbHH, 4},
    {"_isoRelate_emissionProbHD", (DL_FUNC) &_isoRelate_emissionProbHD, 6},
    {"_isoRelate_emissionProbDD", (DL_FUNC) &_isoRelate_emissionProbDD, 4},
    {"_isoRelate_transitionProbHH", (DL_FUNC) &_isoRelate_transitionProbHH, 5},
    {"_isoRelate_transitionProbHD", (DL_FUNC) &_isoRelate_transitionProbHD, 5},
    {"_isoRelate_transitionProbDD", (DL_FUNC) &_isoRelate_transitionProbDD, 7},
    {"_isoRelate_genotypeErrorH", (DL_FUNC) &_isoRelate_genotypeErrorH, 3},
    {"_isoRelate_genotypeErrorD", (DL_FUNC) &_isoRelate_genotypeErrorD, 3},
    {"_isoRelate_trueGenotypes", (DL_FUNC) &_isoRelate_trueGenotypes, 2},
    {"_isoRelate_emissionProbMissingGeno", (DL_FUNC) &_isoRelate_emissionProbMissingGeno, 7},
    {"_isoRelate_calculateAlpha", (DL_FUNC) &_isoRelate_calculateAlpha, 10},
    {"_isoRelate_calculateScale", (DL_FUNC) &_isoRelate_calculateScale, 10},
    {"_isoRelate_calculateBeta", (DL_FUNC) &_isoRelate_calculateBeta, 11},
    {"_isoRelate_calculateViterbi", (DL_FUNC) &_isoRelate_calculateViterbi, 10},
    {"_isoRelate_calculateGamma", (DL_FUNC) &_isoRelate_calculateGamma, 10},
    {"_isoRelate_calculateLogLikelihood", (DL_FUNC) &_isoRelate_calculateLogLikelihood, 10},
    {"_isoRelate_bVectorHH", (DL_FUNC) &_isoRelate_bVectorHH, 1},
    {"_isoRelate_AmatrixHH", (DL_FUNC) &_isoRelate_AmatrixHH, 2},
    {"_isoRelate_bVectorHD", (DL_FUNC) &_isoRelate_bVectorHD, 1},
    {"_isoRelate_AmatrixHD", (DL_FUNC) &_isoRelate_AmatrixHD, 2},
    {"_isoRelate_bVectorDD", (DL_FUNC) &_isoRelate_bVectorDD, 1},
    {"_isoRelate_AmatrixDD", (DL_FUNC) &_isoRelate_AmatrixDD, 2},
    {"_isoRelate_IBDMatrix", (DL_FUNC) &_isoRelate_IBDMatrix, 7},
    {"_isoRelate_calculatePopAlleleFreq", (DL_FUNC) &_isoRelate_calculatePopAlleleFreq, 2},
    {"_isoRelate_calculateMissingness", (DL_FUNC) &_isoRelate_calculateMissingness, 1},
    {"_isoRelate_groupPairs", (DL_FUNC) &_isoRelate_groupPairs, 1},
    {"_isoRelate_isolatePairs", (DL_FUNC) &_isoRelate_isolatePairs, 2},
    {"_isoRelate_haplotypeToGenotype", (DL_FUNC) &_isoRelate_haplotypeToGenotype, 2},
    {"_isoRelate_IBDLabel", (DL_FUNC) &_isoRelate_IBDLabel, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_isoRelate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
