# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Round digits to specified decimal places
#' @param number A number to round
#' @param number The number of digits to round to
roundDecimal <- function(number, digits) {
    .Call('IsoRelate_roundDecimal', PACKAGE = 'IsoRelate', number, digits)
}

#' The emission probabilities for 2 haploid chromosomes
#' @param pop_allele_freq The population allele frequency for SNP i. This corresponds to the reference allele
#' @param genotype_1 The genotype for isolate 1 from the pair for SNP i
#' @param genotype_2 The genotype for isolate 2 from the pair for SNP i
#' @param ibd The IBD state 
emissionProbHH <- function(pop_allele_freq, genotype_1, genotype_2, ibd) {
    .Call('IsoRelate_emissionProbHH', PACKAGE = 'IsoRelate', pop_allele_freq, genotype_1, genotype_2, ibd)
}

#' The emission probabilities for 1 haploid chromosome and 1 diploid chromosome
#' @param pop_allele_freq The population allele frequency for SNP i. This corresponds to the reference allele
#' @param genotype_1 The genotype for isolate 1 from the pair for SNP i
#' @param genotype_2 The genotype for isolate 2 from the pair for SNP i
#' @param ibd The IBD state 
#' @param male_column The haploid isolate from the pair. Either 1 or 2
#' @param female_column The diploid isolate from the pair. Either 1 or 2
emissionProbHD <- function(pop_allele_freq, genotype_1, genotype_2, ibd, male_column, female_column) {
    .Call('IsoRelate_emissionProbHD', PACKAGE = 'IsoRelate', pop_allele_freq, genotype_1, genotype_2, ibd, male_column, female_column)
}

#' The emission probabilities for 2 diploid chromosomes
#' @param pop_allele_freq The population allele frequency for SNP i. This corresponds to the reference allele
#' @param genotype_1 The genotype for isolate 1 from the pair for SNP i
#' @param genotype_2 The genotype for isolate 2 from the pair for SNP i
#' @param ibd The IBD state 
emissionProbDD <- function(pop_allele_freq, genotype_1, genotype_2, ibd) {
    .Call('IsoRelate_emissionProbDD', PACKAGE = 'IsoRelate', pop_allele_freq, genotype_1, genotype_2, ibd)
}

#' The transition probabilities for 2 haploid chromosomes
#' @param omega_0 The probability of sharing 0 alleles IBD
#' @param meiosis The number of meiosis separating the two isoaltes
#' @param dist_cM The genetic map distance (cM) between SNP i and SNP j
#' @param ibd_current The IBD state of SNP j
#' @param ibd_previous The IBD state of SNP i
transitionProbHH <- function(omega_0, meiosis, dist_cM, ibd_current, ibd_previous) {
    .Call('IsoRelate_transitionProbHH', PACKAGE = 'IsoRelate', omega_0, meiosis, dist_cM, ibd_current, ibd_previous)
}

#' The transition probabilities for 1 haploid and 1 diploid chromosome
#' @param omega_0 The probability of sharing 0 alleles IBD
#' @param meiosis The number of meiosis separating the two isoaltes
#' @param dist_cM The genetic map distance (cM) between SNP i and SNP j
#' @param ibd_current The IBD state of SNP j
#' @param ibd_previous The IBD state of SNP i
transitionProbHD <- function(omega_0, meiosis, dist_cM, ibd_current, ibd_previous) {
    .Call('IsoRelate_transitionProbHD', PACKAGE = 'IsoRelate', omega_0, meiosis, dist_cM, ibd_current, ibd_previous)
}

#' The transition probabilities for 2 diploid chromosomes
#' @param omega_0 The probability of sharing 0 alleles IBD
#' @param meiosis The number of meiosis separating the two isoaltes
#' @param dist_cM The genetic map distance (cM) between SNP i and SNP j
#' @param ibd_current The IBD state of SNP j
#' @param ibd_previous The IBD state of SNP i
transitionProbDD <- function(omega_0, omega_1, omega_2, meiosis, dist_cM, ibd_current, ibd_previous) {
    .Call('IsoRelate_transitionProbDD', PACKAGE = 'IsoRelate', omega_0, omega_1, omega_2, meiosis, dist_cM, ibd_current, ibd_previous)
}

#' The genotyping error probability for 1 haploid chromosome
#' @param truth The true genotype
#' @param observed The observed genotype
#' @param error The genotype error rate
genotypeErrorH <- function(truth, observed, error) {
    .Call('IsoRelate_genotypeErrorH', PACKAGE = 'IsoRelate', truth, observed, error)
}

#' The genotyping error probability for 1 diploid chromosome
#' @param truth The true genotype
#' @param observed The observed genotype
#' @param error The genotype error rate
genotypeErrorD <- function(truth, observed, error) {
    .Call('IsoRelate_genotypeErrorD', PACKAGE = 'IsoRelate', truth, observed, error)
}

#' Matrices of all possible genotype combinations between pairs, given MOI
#' @param gender_1 The MOI estimate of isolate 1
#' @param gender_2 The MOI estimate of isolate 2
trueGenotypes <- function(gender_1, gender_2) {
    .Call('IsoRelate_trueGenotypes', PACKAGE = 'IsoRelate', gender_1, gender_2)
}

#' Calculating the emission probability sumation when missing genotype calls present
#' @param pop_allele_freq The population allele frequency of SNP t
#' @param genotype_1 The genotype of isolate 1 at SNP t
#' @param genotype_2 The genotype of isolate 2 at SNP t
#' @param error The genotype error rate
#' @param gender_1 The MOI estimate of isolate 1
#' @param gender_2 The MOI estimate of isolate 2
#' @param ibd_j The IBD state
emissionProbMissingGeno <- function(pop_allele_freq, genotype_1, genotype_2, error, gender_1, gender_2, ibd_j) {
    .Call('IsoRelate_emissionProbMissingGeno', PACKAGE = 'IsoRelate', pop_allele_freq, genotype_1, genotype_2, error, gender_1, gender_2, ibd_j)
}

#' Calculate alpha 
#' @param number_states Integer. The number of IBD states in the model
#' @param initial_prob A numeric vector containing the initial state probabilities
#' @param meiosis Integer. The number of meiosis separating the two isolates
#' @param number_snps Integer. The number of SNPs
#' @param genotypes A integer martix containing the genotype calls for a pair of isolates
#' @param pop_allele_freqs A numeric vector of population allele frequencies
#' @param positions_cM A numeric vector of SNP genetic map positions in cM
#' @param error Numeric. The genotype error rate
#' @param gender_1 Integer. The MOI estimate of isolate 1
#' @param gender_2 Integer. The MOI estimate of isolate 2
calculateAlpha <- function(number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2) {
    .Call('IsoRelate_calculateAlpha', PACKAGE = 'IsoRelate', number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2)
}

#' Calculate scale
#' @param number_states Integer. The number of IBD states in the model
#' @param initial_prob A numeric vector containing the initial state probabilities
#' @param meiosis Integer. The number of meiosis separating the two isolates
#' @param number_snps Integer. The number of SNPs
#' @param genotypes A integer martix containing the genotype calls for a pair of isolates
#' @param pop_allele_freqs A numeric vector of population allele frequencies
#' @param positions_cM A numeric vector of SNP genetic map positions in cM
#' @param error Numeric. The genotype error rate
#' @param gender_1 Integer. The MOI estimate of isolate 1
#' @param gender_2 Integer. The MOI estimate of isolate 2
calculateScale <- function(number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2) {
    .Call('IsoRelate_calculateScale', PACKAGE = 'IsoRelate', number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2)
}

#' Calculate beta
#' @param number_states Integer. The number of IBD states in the model
#' @param initial_prob A numeric vector containing the initial state probabilities
#' @param meiosis Integer. The number of meiosis separating the two isolates
#' @param number_snps Integer. The number of SNPs
#' @param genotypes A integer martix containing the genotype calls for a pair of isolates
#' @param pop_allele_freqs A numeric vector of population allele frequencies
#' @param positions_cM A numeric vector of SNP genetic map positions in cM
#' @param scale A numeric vector containing the scaling values used to scale alpha
#' @param error Numeric. The genotype error rate
#' @param gender_1 Integer. The MOI estimate of isolate 1
#' @param gender_2 Integer. The MOI estimate of isolate 2
calculateBeta <- function(number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, scale, error, gender_1, gender_2) {
    .Call('IsoRelate_calculateBeta', PACKAGE = 'IsoRelate', number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, scale, error, gender_1, gender_2)
}

#' Calculate the Viterbi sequence
#' @param number_states Integer. The number of IBD states in the model
#' @param initial_prob A numeric vector containing the initial state probabilities
#' @param meiosis Integer. The number of meiosis separating the two isolates
#' @param number_snps Integer. The number of SNPs
#' @param genotypes A integer martix containing the genotype calls for a pair of isolates
#' @param pop_allele_freqs A numeric vector of population allele frequencies
#' @param positions_cM A numeric vector of SNP genetic map positions in cM 
#' @param error Numeric. The genotype error rate
#' @param gender_1 Integer. The MOI estimate of isolate 1
#' @param gender_2 Integer. The MOI estimate of isolate 2
calculateViterbi <- function(number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2) {
    .Call('IsoRelate_calculateViterbi', PACKAGE = 'IsoRelate', number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2)
}

#' Calculate gamma
#' @param number_states Integer. The number of IBD states in the model
#' @param initial_prob A numeric vector containing the initial state probabilities
#' @param meiosis Integer. The number of meiosis separating the two isolates
#' @param number_snps Integer. The number of SNPs
#' @param genotypes A integer martix containing the genotype calls for a pair of isolates
#' @param pop_allele_freqs A numeric vector of population allele frequencies
#' @param positions_cM A numeric vector of SNP genetic map positions in cM 
#' @param error Numeric. The genotype error rate
#' @param gender_1 Integer. The MOI estimate of isolate 1
#' @param gender_2 Integer. The MOI estimate of isolate 2
calculateGamma <- function(number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2) {
    .Call('IsoRelate_calculateGamma', PACKAGE = 'IsoRelate', number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2)
}

#' Calculate the log-likelihood of the data
#' @param number_states Integer. The number of IBD states in the model
#' @param initial_prob A numeric vector containing the initial state probabilities
#' @param meiosis Integer. The number of meiosis separating the two isolates
#' @param number_snps Integer. The number of SNPs
#' @param genotypes A integer martix containing the genotype calls for a pair of isolates
#' @param pop_allele_freqs A numeric vector of population allele frequencies
#' @param positions_cM A numeric vector of SNP genetic map positions in cM 
#' @param error Numeric. The genotype error rate
#' @param gender_1 Integer. The MOI estimate of isolate 1
#' @param gender_2 Integer. The MOI estimate of isolate 2
calculateLogLikelihood <- function(number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2) {
    .Call('IsoRelate_calculateLogLikelihood', PACKAGE = 'IsoRelate', number_states, initial_prob, meiosis, number_snps, genotypes, pop_allele_freqs, positions_cM, error, gender_1, gender_2)
}

#' The vector b in the equation Ax=b for 2 haploid chromosomes
#' @param genotypes An integer matrix of genotype calls for a pair of isolates. Each coloumn represents and isolate and each row represents a SNP.
bVectorHH <- function(genotypes) {
    .Call('IsoRelate_bVectorHH', PACKAGE = 'IsoRelate', genotypes)
}

#' The matrix A in the equation Ax=b for 2 haploid chromosomes
#' @param pop_allele_freqs A numeric vector of population allele frequencies for each SNP
#' @param genotypes An integer matrix of genotype calls for a pair of isolates. Each coloumn represents and isolate and each row represents a SNP.
AmatrixHH <- function(pop_allele_freqs, genotypes) {
    .Call('IsoRelate_AmatrixHH', PACKAGE = 'IsoRelate', pop_allele_freqs, genotypes)
}

#' The vector b in the equation Ax=b for 1 haploid chromosome and 1 diploid chromosome
#' @param genotypes An integer matrix of genotype calls for a pair of isolates. Each coloumn represents and isolate and each row represents a SNP.
bVectorHD <- function(genotypes) {
    .Call('IsoRelate_bVectorHD', PACKAGE = 'IsoRelate', genotypes)
}

#' The matrix A in the equation Ax=b for 1 haploid and 1 diploid chromosome
#' @param pop_allele_freqs A numeric vector of population allele frequencies for each SNP
#' @param genotypes An integer matrix of genotype calls for a pair of isolates. Each coloumn represents and isolate and each row represents a SNP.
AmatrixHD <- function(pop_allele_freqs, genotypes) {
    .Call('IsoRelate_AmatrixHD', PACKAGE = 'IsoRelate', pop_allele_freqs, genotypes)
}

#' The vector b in the equation Ax=b for 2 diploid chromosomes
#' @param genotypes An integer matrix of genotype calls for a pair of isolates. Each coloumn represents and isolate and each row represents a SNP.
bVectorDD <- function(genotypes) {
    .Call('IsoRelate_bVectorDD', PACKAGE = 'IsoRelate', genotypes)
}

#' The matrix A in the equation Ax=b for 2 diploid chromosomes
#' @param pop_allele_freqs A numeric vector of population allele frequencies for each SNP
#' @param genotypes An integer matrix of genotype calls for a pair of isolates. Each coloumn represents and isolate and each row represents a SNP.
AmatrixDD <- function(pop_allele_freqs, genotypes) {
    .Call('IsoRelate_AmatrixDD', PACKAGE = 'IsoRelate', pop_allele_freqs, genotypes)
}

#' Binary Matrix of IBD
#' 
#' Creates a binary matrix of IBD (1) and non-IBD (0) with each row representing a single SNP
#' and each column representing a unique pair. The number of rows is equal to the total 
#' number of SNPs and the number of columns is equal to the number of pairs.
#' 
#' @param chromosomes A character vector containing the corresponding chromosome for each SNP
#' @param positions_bp A numeric vector containing the corresponding bp position for each SNP
#' @param number_pairs Numeric. The total number of pairs analysed
#' @param ibd_pairs_colnumbers A numeric vector corresponding to column numbers in the output matrix 
#' where each unique number refers to a unique pair with IBD inferred
#' @param ibd_chromosomes A character vector containing the chromosome for each detected IBD segment
#' @param ibd_start_bp A numeric vector containing the base-pair position for the start of each detected IBD segment
#' @param ibd_stop_bp A numeric vector containing the base-pair position for the end of each detected IBD segment
#' @export
IBDMatrix <- function(chromosomes, positions_bp, number_pairs, ibd_pairs_colnumbers, ibd_chromosomes, ibd_start_bp, ibd_stop_bp) {
    .Call('IsoRelate_IBDMatrix', PACKAGE = 'IsoRelate', chromosomes, positions_bp, number_pairs, ibd_pairs_colnumbers, ibd_chromosomes, ibd_start_bp, ibd_stop_bp)
}

#' Calculate Allele Frequencies for SNPs from Genotype Data
#' 
#' \code{calculatePopAlleleFreq} calculates reference allele frequencies for each SNP given genotype data.
#' 
#' @param genotypes An integer matrix of genotype data of the form -1, 0, 1 and 2 representing missing genotypes, homozygous reference, 
#' heterozygous and homozygous alternative respectively. Each column of \code{genotypes} represents a unique isolate and each row of \code{genotypes}
#' represents a unique SNP.
#' @param moi An integer vector of multiplicity of infection (MOI) estimates for each isoalte. Isolate MOI estimates should be ordered such that value \code{n} of 
#' \code{moi} corresponds to column \code{n} of \code{genotypes}.
#' @export
calculatePopAlleleFreq <- function(genotypes, moi) {
    .Call('IsoRelate_calculatePopAlleleFreq', PACKAGE = 'IsoRelate', genotypes, moi)
}

#' Calculate Missingness Proportions
#' 
#' Calculates the proportion of missing data for each SNPs or each isolate where missing values are denoted by -1. 
#' Missing values are calculated for each column of \code{genotypes} (where columns are isolates and rows are SNPs),
#' however \code{genotypes} can be transposed to calculate missingness proportions for SNPs.
#' 
#' @param genotypes An integer matrix of genotype data of the form -1, 0, 1 and 2 representing missing genotypes, homozygous reference, heterozygous and homozygous alternative respectively.
#' @return A vector of length \code{n} where \code{n} is the number of columns in \code{genotypes}. 
#' @export
calculateMissingness <- function(genotypes) {
    .Call('IsoRelate_calculateMissingness', PACKAGE = 'IsoRelate', genotypes)
}

#' Group Combinations for Analysis
#' 
#' Creates a data frame containing family IDs and isolate IDs for each pair to be analysed. Each row
#' corresponds to a unique pair.
#' 
#' @param group A character vector of all family IDs
#' @export
groupPairs <- function(group) {
    .Call('IsoRelate_groupPairs', PACKAGE = 'IsoRelate', group)
}

#' Pair Combinations for Analysis
#' 
#' Creates a data frame containing family IDs and isolate IDs for each pair to be analysed. Each row
#' corresponds to a unique pair.
#' 
#' @param fid A character vector of all family IDs
#' @param iid A character vector of all individual ID
#' @export
isolatePairs <- function(fid, iid) {
    .Call('IsoRelate_isolatePairs', PACKAGE = 'IsoRelate', fid, iid)
}

#' Call Genotypes from Haplotype Data
#' 
#' \code{haplotypeToGenotype} transforms PLINK haplotype data into genotype data of the form -1, 0, 1 and 2 representing missing genotypes,
#' homozygous reference, heterozygous and homozygous alternative respectively. Haploid isolates are coded as diploid although will not have
#' heterozygous genotypes.
#' 
#' @param haplotypes An integer matrix of haplotype data in PLINK format. A allele is denoted 1, B allele is denoted 2 and missing data is denoted 0
#' @param moi An integer vector of multiplicity of infection (MOI) estimates for each isoalte. Isolate MOI estimates should be ordered such that value \code{n} of 
#' \code{moi} corresponds to column \code{n} of \code{haplotypes}.
#' @return A matrix with genotype calls where columns correspond to isolates and rows correspond to SNPs
haplotypeToGenotype <- function(haplotypes, moi) {
    .Call('IsoRelate_haplotypeToGenotype', PACKAGE = 'IsoRelate', haplotypes, moi)
}

#' Internal Function
#' 
#' \code{IBDLabel} is a function used to label unique IBD segments in a pair of isolates for a particular chromosome by determining 
#' breakpoints in IBD vs non-IBD regions. IBD segments are labelled in sequential order genome wide.
#' 
#' @param snp_id A numeric vector of SNP identifiers for IBD segments on the chromosome of interest.
#' @param number_snps integer. The number of IBD SNPs for the chromosome of interest.
IBDLabel <- function(snp_id, number_snps) {
    .Call('IsoRelate_IBDLabel', PACKAGE = 'IsoRelate', snp_id, number_snps)
}

#' Round digits to specified decimal places
#' @param number A number to round
#' @param number The number of digits to round to
roundDecimal_w <- function(number, digits) {
    .Call('IsoRelate_roundDecimal_w', PACKAGE = 'IsoRelate', number, digits)
}

#' The emission probability for isolate i, SNP j in state k.
#' @param BAFvalue A vector of length 1 with the BAF value for isolate i, SNP j
#' @param meanBAF0 A vector of possible major clone proportions
#' @param sdBAF0 A vector of standard deviations for; one for each major clone proportion
#' @param state0 The IBD state 
#' @param pfb The population BAF for SNP j
BAFemprobs <- function(BAFvalue, meanBAF0, sdBAF0, state0, pfb) {
    .Call('IsoRelate_BAFemprobs', PACKAGE = 'IsoRelate', BAFvalue, meanBAF0, sdBAF0, state0, pfb)
}

#' The emission probabilities for isolate i calculated over all SNPs and states
#' @param BAFmatrix A vector of BAF values for isolate i
#' @param alleleFreq A vector of population BAF values
#' @param BAFmean A vector of possible major clone proportions
#' @param BAFsd A vector of standard deviations for; one for each major clone proportion
#' @param positionBP A vector of genetic map positions for all SNPs in base-pairs
#' @param bin A matrix of bins with parameter estimates (proportion estimates with corresponding SD)
calculate_em_probs <- function(BAFmatrix, alleleFreq, BAFmean, BAFsd, positionBP, bin) {
    .Call('IsoRelate_calculate_em_probs', PACKAGE = 'IsoRelate', BAFmatrix, alleleFreq, BAFmean, BAFsd, positionBP, bin)
}

#' The transition probabilities for 2 haploid chromosomes
#' @param dist The distance between adjacent SNPs
#' @param transParam A matrix of transition rate probabilities
transMatrix <- function(dist, transParam) {
    .Call('IsoRelate_transMatrix', PACKAGE = 'IsoRelate', dist, transParam)
}

#' Calculate alpha 
#' @param emissionProbs A numeric matrix of pre-calculated emission probabilities for each state and SNP
#' @param initalProbs A numeric vector of initial state probabilities. One probability per state
#' @param positionBP A vector of genetic map positions in base-pairs
#' @param transParam A matrix of transition probabilities
calculate_alpha_w <- function(emissionProbs, initalProbs, positionBP, transParam) {
    .Call('IsoRelate_calculate_alpha_w', PACKAGE = 'IsoRelate', emissionProbs, initalProbs, positionBP, transParam)
}

#' Calculate scale
#' @param emissionProbs A numeric matrix of pre-calculated emission probabilities for each state and SNP
#' @param initalProbs A numeric vector of initial state probabilities. One probability per state
#' @param positionBP A vector of genetic map positions in base-pairs
#' @param transParam A matrix of transition probabilities
calculate_scale_w <- function(emissionProbs, initalProbs, positionBP, transParam) {
    .Call('IsoRelate_calculate_scale_w', PACKAGE = 'IsoRelate', emissionProbs, initalProbs, positionBP, transParam)
}

#' Calculate beta
#' @param emissionProbs A numeric matrix of pre-calculated emission probabilities for each state and SNP
#' @param initalProbs A numeric vector of initial state probabilities. One probability per state
#' @param positionBP A vector of genetic map positions in base-pairs
#' @param transParam A matrix of transition probabilities
#' @param scale A vector of scaling values used to scale alpha
calculate_beta_w <- function(emissionProbs, initalProbs, positionBP, transParam, scale) {
    .Call('IsoRelate_calculate_beta_w', PACKAGE = 'IsoRelate', emissionProbs, initalProbs, positionBP, transParam, scale)
}

#' Calculate gamma
#' @param alpha A matrix of alpha values calculated from the forward algorithm
#' @param beta A matrix of beta values calculated from the backward algorithm
calculate_gamma_w <- function(alpha, beta) {
    .Call('IsoRelate_calculate_gamma_w', PACKAGE = 'IsoRelate', alpha, beta)
}

#' Calculate the Viterbi sequence
#' @param emissionProbs A numeric matrix of pre-calculated emission probabilities for each state and SNP
#' @param initalProbs A numeric vector of initial state probabilities. One probability per state
#' @param positionBP A vector of genetic map positions in base-pairs
#' @param transParam A matrix of transition probabilities
calculate_viterbi_w <- function(emissionProbs, initalProbs, positionBP, transParam) {
    .Call('IsoRelate_calculate_viterbi_w', PACKAGE = 'IsoRelate', emissionProbs, initalProbs, positionBP, transParam)
}

#' Calculate the Xi
#' @param emissionProbs A numeric matrix of pre-calculated emission probabilities for each state and SNP
#' @param positionBP A vector of genetic map positions in base-pairs
#' @param transParam A matrix of transition probabilities
#' @param alpha A matrix of alpha values calculated from the forward algorithm
#' @param beta A matrix of alpha values calculated from the backward algorithm
calculate_xi <- function(emissionProbs, positionBP, transParam, alpha, beta) {
    .Call('IsoRelate_calculate_xi', PACKAGE = 'IsoRelate', emissionProbs, positionBP, transParam, alpha, beta)
}

#' Re-estimate the transition probabilities
#' @param xi A numeric matrix of xi values
#' @param gamma A numeric matrix of gamma values (posterior probabilities)
reest_transition <- function(xi, gamma) {
    .Call('IsoRelate_reest_transition', PACKAGE = 'IsoRelate', xi, gamma)
}

#' Calculate the log-likelihood
#' @param scale A vector of scaling values used to scale alpha
calculate_logLikelihood_w <- function(scale) {
    .Call('IsoRelate_calculate_logLikelihood_w', PACKAGE = 'IsoRelate', scale)
}

#' Calculate the Baum-Welch algorithm
#' @param emissionProbs A numeric matrix of pre-calculated emission probabilities for each state and SNP
#' @param initalProbs A numeric vector of initial state probabilities. One probability per state
#' @param positionBP A vector of genetic map positions in base-pairs
#' @param transParam A matrix of transition probabilities
calculate_BaumWelch <- function(emissionProbs, initalProbs, positionBP, transParam) {
    .Call('IsoRelate_calculate_BaumWelch', PACKAGE = 'IsoRelate', emissionProbs, initalProbs, positionBP, transParam)
}

